--- #YAML:1.0
name:               Covetel-LDAP
version:            0.02
abstract:           Covetel::LDAP base class
author:
    - Walter Vargas <wvargas@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
    Net::LDAP: 0
    Net::LDAPS: 0
    Config::Any::INI: 0
    Digest::SHA1: 0
    Unicode::Map8: 0
    Unicode::String: 0
    IO::Socket::SSL: 0
requires:
    Test::More:  0
    ExtUtils::MakeMaker:  0
    Net::LDAP: 0
    Net::LDAPS: 0
    Config::Any::INI: 0
    Digest::SHA1: 0
    Unicode::Map8: 0
    Unicode::String: 0
    IO::Socket::SSL: 0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
